import { jsPDF } from 'jspdf';
import { formatCurrency } from './auctionStorage';

export function downloadWinnerPDF(auction, winner, currency = 'USD') {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageW = pdf.internal.pageSize.getWidth();
  let y = 20;

  // --- Header Bar ---
  pdf.setFillColor(79, 70, 229); // Indigo
  pdf.rect(0, 0, pageW, 40, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text('AUCTION WINNER CERTIFICATE', pageW / 2, 18, { align: 'center' });
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Official Auction Completion Report', pageW / 2, 28, { align: 'center' });
  pdf.text(`Generated: ${new Date().toLocaleString()}`, pageW / 2, 35, { align: 'center' });

  y = 52;

  // --- Auction Info Section ---
  pdf.setTextColor(30, 30, 30);
  pdf.setFillColor(243, 244, 246);
  pdf.roundedRect(14, y, pageW - 28, 55, 4, 4, 'F');

  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(79, 70, 229);
  pdf.text('AUCTION DETAILS', 20, y + 10);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(60, 60, 60);

  const auctionTitle = auction.title || auction.name || 'Untitled Auction';
  const auctionId = auction.id || 'N/A';
  const host = auction.createdBy || 'Unknown';
  const basePriceStr = formatCurrency(auction.basePrice || 0, currency);
  const maxBidders = auction.maxBidders || 'N/A';
  const status = (auction.status || 'ended').toUpperCase();

  pdf.text(`Title: ${auctionTitle}`, 20, y + 20);
  pdf.text(`Auction ID: ${auctionId}`, 20, y + 27);
  pdf.text(`Host: ${host}`, 20, y + 34);
  pdf.text(`Base Price: ${basePriceStr}`, pageW / 2, y + 20);
  pdf.text(`Max Bidders: ${maxBidders}`, pageW / 2, y + 27);
  pdf.text(`Status: ${status}`, pageW / 2, y + 34);

  if (auction.description) {
    const descLines = pdf.splitTextToSize(`Description: ${auction.description}`, pageW - 44);
    pdf.text(descLines.slice(0, 2), 20, y + 44);
  }

  y += 62;

  // --- Winner Section ---
  pdf.setFillColor(34, 197, 94);
  pdf.roundedRect(14, y, pageW - 28, 45, 4, 4, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('WINNER', pageW / 2, y + 12, { align: 'center' });

  if (winner) {
    pdf.setFontSize(20);
    pdf.text(winner.bidder?.name || 'Unknown', pageW / 2, y + 25, { align: 'center' });
    pdf.setFontSize(14);
    pdf.text(`Winning Bid: ${formatCurrency(winner.bid || 0, currency)}`, pageW / 2, y + 36, { align: 'center' });
  } else {
    pdf.setFontSize(14);
    pdf.text('No bids were placed', pageW / 2, y + 28, { align: 'center' });
  }

  y += 55;

  // --- All Participants Summary ---
  const bidders = auction.bidders || [];
  if (bidders.length > 0) {
    pdf.setTextColor(30, 30, 30);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(79, 70, 229);
    pdf.text('PARTICIPANTS SUMMARY', 20, y);
    y += 8;

    // Table header
    pdf.setFillColor(79, 70, 229);
    pdf.rect(14, y, pageW - 28, 8, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.text('#', 18, y + 5.5);
    pdf.text('Bidder Name', 30, y + 5.5);
    pdf.text('Last Bid', pageW / 2 + 10, y + 5.5);
    pdf.text('Status', pageW - 40, y + 5.5);
    y += 10;

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 60);
    bidders
      .slice()
      .sort((a, b) => (b.lastBid || 0) - (a.lastBid || 0))
      .forEach((b, idx) => {
        if (y > 270) {
          pdf.addPage();
          y = 20;
        }
        const isEven = idx % 2 === 0;
        if (isEven) {
          pdf.setFillColor(249, 250, 251);
          pdf.rect(14, y - 3, pageW - 28, 8, 'F');
        }
        pdf.text(`${idx + 1}`, 18, y + 2);
        pdf.text(b.name || 'Unknown', 30, y + 2);
        pdf.text(formatCurrency(b.lastBid || 0, currency), pageW / 2 + 10, y + 2);
        pdf.text((b.status || 'active').toUpperCase(), pageW - 40, y + 2);
        y += 8;
      });
  }

  y += 10;

  // --- Footer ---
  if (y > 260) { pdf.addPage(); y = 20; }
  pdf.setDrawColor(200, 200, 200);
  pdf.line(14, y, pageW - 14, y);
  y += 8;
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text('This document was automatically generated by Auction Hub.', pageW / 2, y, { align: 'center' });
  pdf.text(`Report Date: ${new Date().toISOString()}`, pageW / 2, y + 5, { align: 'center' });

  // Save
  const filename = `auction-${auction.id || 'report'}-winner.pdf`;
  pdf.save(filename);
}
